// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Lion struct {
	ID     string `json:"_id" bson:"_id"`
	Name   string `json:"name"`
	IsKing bool   `json:"isKing"`
}

type NewLion struct {
	Name   string `json:"name"`
	IsKing bool   `json:"isKing"`
}
